# openjdk11のイメージを利用。
FROM maven:3.8.6-openjdk-18
 
# # ローカルのソースコードをマウントするためのディレクトリを作成。
# RUN mkdir /opt/project
 
# # tomcatをダウンロードして/usr/localに配置、mavenもインストールしておく。
# RUN curl -sL https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.58/bin/apache-tomcat-9.0.58.tar.gz
